apiVersion: v1
data:
  GITHUB_SHA: 168dd5455fa4466dc970f2151ce77143b6642c20
  NAMESPACE: pr-110
  OVERLAY: staging
  SERVICE_NAME: service-bar
kind: ConfigMap
metadata:
  name: service-bar-metadata-hb5ddmkd27
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-bar
  name: service-bar
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: service-bar
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-bar
  name: service-bar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-bar
  template:
    metadata:
      labels:
        app: service-bar
    spec:
      containers:
      - image: ghcr.io/yuya-takeyama/monorepo/service-bar:pr-110.168dd5455fa4466dc970f2151ce77143b6642c20
        name: service-bar
