apiVersion: v1
data:
  GITHUB_SHA: d70acb6c0bc0821e9f90f00da2bdb76feef875be
  NAMESPACE: staging
  OVERLAY: staging
  SERVICE_NAME: service-foo
kind: ConfigMap
metadata:
  name: service-foo-metadata-64gt5b2hhf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-foo
  name: service-foo
spec:
  ports:
  - name: 80-4567
    port: 80
    protocol: TCP
    targetPort: 4567
  selector:
    app: service-foo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-foo
  name: service-foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-foo
  template:
    metadata:
      labels:
        app: service-foo
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: service-foo-metadata-64gt5b2hhf
        image: service-foo
        name: service-foo
